//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace WebProgramAR.Entidades
{
    public partial class EstadoEjercicio
    {
        #region Primitive Properties
    
        public virtual int EstadoEjercicioId
        {
            get;
            set;
        }
    
        public virtual string Descripcion
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Ejercicio> Ejercicio
        {
            get
            {
                if (_ejercicio == null)
                {
                    var newCollection = new FixupCollection<Ejercicio>();
                    newCollection.CollectionChanged += FixupEjercicio;
                    _ejercicio = newCollection;
                }
                return _ejercicio;
            }
            set
            {
                if (!ReferenceEquals(_ejercicio, value))
                {
                    var previousValue = _ejercicio as FixupCollection<Ejercicio>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupEjercicio;
                    }
                    _ejercicio = value;
                    var newValue = value as FixupCollection<Ejercicio>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupEjercicio;
                    }
                }
            }
        }
        private ICollection<Ejercicio> _ejercicio;

        #endregion
        #region Association Fixup
    
        private void FixupEjercicio(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Ejercicio item in e.NewItems)
                {
                    item.EstadoEjercicio = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Ejercicio item in e.OldItems)
                {
                    if (ReferenceEquals(item.EstadoEjercicio, this))
                    {
                        item.EstadoEjercicio = null;
                    }
                }
            }
        }

        #endregion
    }
}
