//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace WebProgramAR.Entidades
{
    public partial class Pais
    {
        #region Primitive Properties
    
        public virtual string PaisId
        {
            get;
            set;
        }
    
        public virtual string Descripcion
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Localidad> Localidad
        {
            get
            {
                if (_localidad == null)
                {
                    var newCollection = new FixupCollection<Localidad>();
                    newCollection.CollectionChanged += FixupLocalidad;
                    _localidad = newCollection;
                }
                return _localidad;
            }
            set
            {
                if (!ReferenceEquals(_localidad, value))
                {
                    var previousValue = _localidad as FixupCollection<Localidad>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupLocalidad;
                    }
                    _localidad = value;
                    var newValue = value as FixupCollection<Localidad>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupLocalidad;
                    }
                }
            }
        }
        private ICollection<Localidad> _localidad;
    
        public virtual ICollection<Provincia> Provincia
        {
            get
            {
                if (_provincia == null)
                {
                    var newCollection = new FixupCollection<Provincia>();
                    newCollection.CollectionChanged += FixupProvincia;
                    _provincia = newCollection;
                }
                return _provincia;
            }
            set
            {
                if (!ReferenceEquals(_provincia, value))
                {
                    var previousValue = _provincia as FixupCollection<Provincia>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupProvincia;
                    }
                    _provincia = value;
                    var newValue = value as FixupCollection<Provincia>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupProvincia;
                    }
                }
            }
        }
        private ICollection<Provincia> _provincia;
    
        public virtual ICollection<Usuario> Usuarios
        {
            get
            {
                if (_usuarios == null)
                {
                    var newCollection = new FixupCollection<Usuario>();
                    newCollection.CollectionChanged += FixupUsuarios;
                    _usuarios = newCollection;
                }
                return _usuarios;
            }
            set
            {
                if (!ReferenceEquals(_usuarios, value))
                {
                    var previousValue = _usuarios as FixupCollection<Usuario>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupUsuarios;
                    }
                    _usuarios = value;
                    var newValue = value as FixupCollection<Usuario>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupUsuarios;
                    }
                }
            }
        }
        private ICollection<Usuario> _usuarios;

        #endregion
        #region Association Fixup
    
        private void FixupLocalidad(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Localidad item in e.NewItems)
                {
                    item.Pais = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Localidad item in e.OldItems)
                {
                    if (ReferenceEquals(item.Pais, this))
                    {
                        item.Pais = null;
                    }
                }
            }
        }
    
        private void FixupProvincia(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Provincia item in e.NewItems)
                {
                    item.Pais = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Provincia item in e.OldItems)
                {
                    if (ReferenceEquals(item.Pais, this))
                    {
                        item.Pais = null;
                    }
                }
            }
        }
    
        private void FixupUsuarios(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Usuario item in e.NewItems)
                {
                    item.Pais = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Usuario item in e.OldItems)
                {
                    if (ReferenceEquals(item.Pais, this))
                    {
                        item.Pais = null;
                    }
                }
            }
        }

        #endregion
    }
}
