//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace WebProgramAR.Entidades
{
    public partial class Provincia
    {
        #region Primitive Properties
    
        public virtual string ProvinciaId
        {
            get;
            set;
        }
    
        public virtual string Descripcion
        {
            get;
            set;
        }
    
        public virtual string PaisId
        {
            get { return _paisId; }
            set
            {
                if (_paisId != value)
                {
                    if (Pais != null && Pais.PaisId != value)
                    {
                        Pais = null;
                    }
                    _paisId = value;
                }
            }
        }
        private string _paisId;

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Localidad> Localidad
        {
            get
            {
                if (_localidad == null)
                {
                    var newCollection = new FixupCollection<Localidad>();
                    newCollection.CollectionChanged += FixupLocalidad;
                    _localidad = newCollection;
                }
                return _localidad;
            }
            set
            {
                if (!ReferenceEquals(_localidad, value))
                {
                    var previousValue = _localidad as FixupCollection<Localidad>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupLocalidad;
                    }
                    _localidad = value;
                    var newValue = value as FixupCollection<Localidad>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupLocalidad;
                    }
                }
            }
        }
        private ICollection<Localidad> _localidad;
    
        public virtual Pais Pais
        {
            get { return _pais; }
            set
            {
                if (!ReferenceEquals(_pais, value))
                {
                    var previousValue = _pais;
                    _pais = value;
                    FixupPais(previousValue);
                }
            }
        }
        private Pais _pais;
    
        public virtual ICollection<Usuario> Usuario
        {
            get
            {
                if (_usuario == null)
                {
                    var newCollection = new FixupCollection<Usuario>();
                    newCollection.CollectionChanged += FixupUsuario;
                    _usuario = newCollection;
                }
                return _usuario;
            }
            set
            {
                if (!ReferenceEquals(_usuario, value))
                {
                    var previousValue = _usuario as FixupCollection<Usuario>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupUsuario;
                    }
                    _usuario = value;
                    var newValue = value as FixupCollection<Usuario>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupUsuario;
                    }
                }
            }
        }
        private ICollection<Usuario> _usuario;

        #endregion
        #region Association Fixup
    
        private void FixupPais(Pais previousValue)
        {
            if (previousValue != null && previousValue.Provincia.Contains(this))
            {
                previousValue.Provincia.Remove(this);
            }
    
            if (Pais != null)
            {
                if (!Pais.Provincia.Contains(this))
                {
                    Pais.Provincia.Add(this);
                }
                if (PaisId != Pais.PaisId)
                {
                    PaisId = Pais.PaisId;
                }
            }
        }
    
        private void FixupLocalidad(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Localidad item in e.NewItems)
                {
                    item.Provincia = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Localidad item in e.OldItems)
                {
                    if (ReferenceEquals(item.Provincia, this))
                    {
                        item.Provincia = null;
                    }
                }
            }
        }
    
        private void FixupUsuario(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Usuario item in e.NewItems)
                {
                    item.Provincia = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Usuario item in e.OldItems)
                {
                    if (ReferenceEquals(item.Provincia, this))
                    {
                        item.Provincia = null;
                    }
                }
            }
        }

        #endregion
    }
}
