//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace WebProgramAR.Entidades
{
    public partial class Tabla
    {
        #region Primitive Properties
    
        public virtual int TablaId
        {
            get;
            set;
        }
    
        public virtual string Nombre
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Columna> Columnas
        {
            get
            {
                if (_columnas == null)
                {
                    var newCollection = new FixupCollection<Columna>();
                    newCollection.CollectionChanged += FixupColumnas;
                    _columnas = newCollection;
                }
                return _columnas;
            }
            set
            {
                if (!ReferenceEquals(_columnas, value))
                {
                    var previousValue = _columnas as FixupCollection<Columna>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupColumnas;
                    }
                    _columnas = value;
                    var newValue = value as FixupCollection<Columna>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupColumnas;
                    }
                }
            }
        }
        private ICollection<Columna> _columnas;
    
        public virtual ICollection<ReglasSeguridad> ReglasSeguridads
        {
            get
            {
                if (_reglasSeguridads == null)
                {
                    var newCollection = new FixupCollection<ReglasSeguridad>();
                    newCollection.CollectionChanged += FixupReglasSeguridads;
                    _reglasSeguridads = newCollection;
                }
                return _reglasSeguridads;
            }
            set
            {
                if (!ReferenceEquals(_reglasSeguridads, value))
                {
                    var previousValue = _reglasSeguridads as FixupCollection<ReglasSeguridad>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupReglasSeguridads;
                    }
                    _reglasSeguridads = value;
                    var newValue = value as FixupCollection<ReglasSeguridad>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupReglasSeguridads;
                    }
                }
            }
        }
        private ICollection<ReglasSeguridad> _reglasSeguridads;

        #endregion
        #region Association Fixup
    
        private void FixupColumnas(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Columna item in e.NewItems)
                {
                    item.Tabla = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Columna item in e.OldItems)
                {
                    if (ReferenceEquals(item.Tabla, this))
                    {
                        item.Tabla = null;
                    }
                }
            }
        }
    
        private void FixupReglasSeguridads(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ReglasSeguridad item in e.NewItems)
                {
                    item.Tabla = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ReglasSeguridad item in e.OldItems)
                {
                    if (ReferenceEquals(item.Tabla, this))
                    {
                        item.Tabla = null;
                    }
                }
            }
        }

        #endregion
    }
}
