//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompiladorGargar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CompiladorGargar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 564
        ///20
        ///pp0
        ///a1..a2..af3..a4..a5..a6..a7..a8..af9
        ///b1..b2..b3..b4..b5..b6..b7..bf8
        ///c1..c2..c3..c4..c5..c6..c7..cf8..c9..c10..cf11..c12..c13..c14..c15..cf16
        ///e1..e2..e3..e7..e8..e9..e10..ef11
        ///d1..df2
        ///f1..f2..f3..f4..ff5..f6..f7..f8..f9..f10..ff11..f12..f13..f14..f15..f16..f17..f18..ff19..f20..f21..f22..ff23..f24..ff25..f26..f27..f28..f29..f30..ff31
        ///h1..h2..h3..h4..hf5
        ///l1..l2..l3..lf4..l5..l6..l7..l8..lf9
        ///m1..m2..m3..m4..m5..m6..m7..mf8..m9..m10..m11..m12..m13..mf14
        ///n1..n2..n3..n4..n5..nf6
        ///o1..of2
        ///p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AFD_GARGAR {
            get {
                return ResourceManager.GetString("AFD_GARGAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string CantElementosCadenaEntrada {
            get {
                return ResourceManager.GetString("CantElementosCadenaEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        internal static string CapacidadBuffer {
            get {
                return ResourceManager.GetString("CapacidadBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string ExtraEspaciosEnBuffer {
            get {
                return ResourceManager.GetString("ExtraEspaciosEnBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Gramatica&gt;
        ///	&lt;!--red--&gt;
        ///	&lt;NoTerminales&gt;
        ///		&lt;NoTerminal&gt;START&lt;/NoTerminal&gt;
        ///		&lt;NoTerminal&gt;DECLARACIONESINI&lt;/NoTerminal&gt;
        ///		&lt;NoTerminal&gt;DECLARACIONES&lt;/NoTerminal&gt;
        ///		&lt;NoTerminal&gt;PROCEDIMIENTOS&lt;/NoTerminal&gt;
        ///		&lt;NoTerminal&gt;CONSTANTES&lt;/NoTerminal&gt;
        ///		&lt;NoTerminal&gt;VARIABLES&lt;/NoTerminal&gt;
        ///		&lt;NoTerminal&gt;C&lt;/NoTerminal&gt;
        ///		&lt;NoTerminal&gt;TIPODATO&lt;/NoTerminal&gt;
        ///		&lt;NoTerminal&gt;NUMERO&lt;/NoTerminal&gt;
        ///		&lt;NoTerminal&gt;VARS&lt;/NoTerminal&gt;
        ///		&lt;NoTerminal&gt;V&lt;/NoTerminal&gt;
        ///		&lt;NoTerminal&gt;IDENT&lt;/NoTerminal&gt;
        ///		&lt;NoTerminal&gt;ID&lt;/NoTerminal&gt;
        ///		&lt;NoTerminal&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Gramatica {
            get {
                return ResourceManager.GetString("Gramatica", resourceCulture);
            }
        }
    }
}
