//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace WebProgramAR.Entidades
{
    public partial class Mail
    {
        #region Primitive Properties
    
        public virtual string From
        {
            get;
            set;
        }
    
        public virtual string To
        {
            get;
            set;
        }
    
        public virtual string Subject
        {
            get;
            set;
        }
    
        public virtual string Body
        {
            get;
            set;
        }
    
        public virtual System.DateTime FechaCreacion
        {
            get;
            set;
        }
    
        public virtual bool Enviado
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> FechaEnvio
        {
            get;
            set;
        }
    
        public virtual int id
        {
            get;
            set;
        }

        #endregion
    }
}
