//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace WebProgramAR.Entidades
{
    public partial class MensajeModeracion
    {
        #region Primitive Properties
    
        public virtual int MensajeModeracionId
        {
            get { return _mensajeModeracionId; }
            set
            {
                if (_mensajeModeracionId != value)
                {
                    if (Ejercicio != null && Ejercicio.EjercicioId != value)
                    {
                        Ejercicio = null;
                    }
                    _mensajeModeracionId = value;
                }
            }
        }
        private int _mensajeModeracionId;
    
        public virtual int UsuarioModeradorId
        {
            get { return _usuarioModeradorId; }
            set
            {
                if (_usuarioModeradorId != value)
                {
                    if (Usuario != null && Usuario.UsuarioId != value)
                    {
                        Usuario = null;
                    }
                    _usuarioModeradorId = value;
                }
            }
        }
        private int _usuarioModeradorId;
    
        public virtual int EjercicioId
        {
            get;
            set;
        }
    
        public virtual string Mensaje
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Ejercicio Ejercicio
        {
            get { return _ejercicio; }
            set
            {
                if (!ReferenceEquals(_ejercicio, value))
                {
                    var previousValue = _ejercicio;
                    _ejercicio = value;
                    FixupEjercicio(previousValue);
                }
            }
        }
        private Ejercicio _ejercicio;
    
        public virtual Usuario Usuario
        {
            get { return _usuario; }
            set
            {
                if (!ReferenceEquals(_usuario, value))
                {
                    var previousValue = _usuario;
                    _usuario = value;
                    FixupUsuario(previousValue);
                }
            }
        }
        private Usuario _usuario;

        #endregion
        #region Association Fixup
    
        private void FixupEjercicio(Ejercicio previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.MensajeModeracion, this))
            {
                previousValue.MensajeModeracion = null;
            }
    
            if (Ejercicio != null)
            {
                Ejercicio.MensajeModeracion = this;
                if (MensajeModeracionId != Ejercicio.EjercicioId)
                {
                    MensajeModeracionId = Ejercicio.EjercicioId;
                }
            }
        }
    
        private void FixupUsuario(Usuario previousValue)
        {
            if (previousValue != null && previousValue.MensajeModeracions.Contains(this))
            {
                previousValue.MensajeModeracions.Remove(this);
            }
    
            if (Usuario != null)
            {
                if (!Usuario.MensajeModeracions.Contains(this))
                {
                    Usuario.MensajeModeracions.Add(this);
                }
                if (UsuarioModeradorId != Usuario.UsuarioId)
                {
                    UsuarioModeradorId = Usuario.UsuarioId;
                }
            }
        }

        #endregion
    }
}
