//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace WebProgramAR.Entidades
{
    public partial class MensajeModeracion
    {
        #region Primitive Properties
    
        public virtual int EjercicioId
        {
            get { return _ejercicioId; }
            set
            {
                if (_ejercicioId != value)
                {
                    if (Ejercicio != null && Ejercicio.EjercicioId != value)
                    {
                        Ejercicio = null;
                    }
                    _ejercicioId = value;
                }
            }
        }
        private int _ejercicioId;
    
        public virtual string Mensaje
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Ejercicio Ejercicio
        {
            get { return _ejercicio; }
            set
            {
                if (!ReferenceEquals(_ejercicio, value))
                {
                    var previousValue = _ejercicio;
                    _ejercicio = value;
                    FixupEjercicio(previousValue);
                }
            }
        }
        private Ejercicio _ejercicio;

        #endregion
        #region Association Fixup
    
        private void FixupEjercicio(Ejercicio previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.MensajeModeracion, this))
            {
                previousValue.MensajeModeracion = null;
            }
    
            if (Ejercicio != null)
            {
                Ejercicio.MensajeModeracion = this;
                if (EjercicioId != Ejercicio.EjercicioId)
                {
                    EjercicioId = Ejercicio.EjercicioId;
                }
            }
        }

        #endregion
    }
}
