//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace WebProgramAR.Entidades
{
    public partial class NivelEjercicio
    {
        #region Primitive Properties
    
        public virtual int NivelEjercicioId
        {
            get;
            set;
        }
    
        public virtual string Descripcion
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Ejercicio> Ejercicios
        {
            get
            {
                if (_ejercicios == null)
                {
                    var newCollection = new FixupCollection<Ejercicio>();
                    newCollection.CollectionChanged += FixupEjercicios;
                    _ejercicios = newCollection;
                }
                return _ejercicios;
            }
            set
            {
                if (!ReferenceEquals(_ejercicios, value))
                {
                    var previousValue = _ejercicios as FixupCollection<Ejercicio>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupEjercicios;
                    }
                    _ejercicios = value;
                    var newValue = value as FixupCollection<Ejercicio>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupEjercicios;
                    }
                }
            }
        }
        private ICollection<Ejercicio> _ejercicios;

        #endregion
        #region Association Fixup
    
        private void FixupEjercicios(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Ejercicio item in e.NewItems)
                {
                    item.NivelEjercicio = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Ejercicio item in e.OldItems)
                {
                    if (ReferenceEquals(item.NivelEjercicio, this))
                    {
                        item.NivelEjercicio = null;
                    }
                }
            }
        }

        #endregion
    }
}
