//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace WebProgramAR.Entidades
{
    public partial class TipoUsuario
    {
        #region Primitive Properties
    
        public virtual int TipoUsuarioId
        {
            get;
            set;
        }
    
        public virtual string Descripcion
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<ReglasSeguridad> ReglasSeguridads
        {
            get
            {
                if (_reglasSeguridads == null)
                {
                    var newCollection = new FixupCollection<ReglasSeguridad>();
                    newCollection.CollectionChanged += FixupReglasSeguridads;
                    _reglasSeguridads = newCollection;
                }
                return _reglasSeguridads;
            }
            set
            {
                if (!ReferenceEquals(_reglasSeguridads, value))
                {
                    var previousValue = _reglasSeguridads as FixupCollection<ReglasSeguridad>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupReglasSeguridads;
                    }
                    _reglasSeguridads = value;
                    var newValue = value as FixupCollection<ReglasSeguridad>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupReglasSeguridads;
                    }
                }
            }
        }
        private ICollection<ReglasSeguridad> _reglasSeguridads;
    
        public virtual ICollection<Usuario> Usuarios
        {
            get
            {
                if (_usuarios == null)
                {
                    var newCollection = new FixupCollection<Usuario>();
                    newCollection.CollectionChanged += FixupUsuarios;
                    _usuarios = newCollection;
                }
                return _usuarios;
            }
            set
            {
                if (!ReferenceEquals(_usuarios, value))
                {
                    var previousValue = _usuarios as FixupCollection<Usuario>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupUsuarios;
                    }
                    _usuarios = value;
                    var newValue = value as FixupCollection<Usuario>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupUsuarios;
                    }
                }
            }
        }
        private ICollection<Usuario> _usuarios;

        #endregion
        #region Association Fixup
    
        private void FixupReglasSeguridads(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ReglasSeguridad item in e.NewItems)
                {
                    item.TipoUsuario = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ReglasSeguridad item in e.OldItems)
                {
                    if (ReferenceEquals(item.TipoUsuario, this))
                    {
                        item.TipoUsuario = null;
                    }
                }
            }
        }
    
        private void FixupUsuarios(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Usuario item in e.NewItems)
                {
                    item.TipoUsuario = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Usuario item in e.OldItems)
                {
                    if (ReferenceEquals(item.TipoUsuario, this))
                    {
                        item.TipoUsuario = null;
                    }
                }
            }
        }

        #endregion
    }
}
